# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: ALEX ARCHIVES


# Below the site title
tagline: Dream for Digital Nomad.

# Site logo
logo: 

# A description of your site for social meta tag, search engines, and feed.xml
description: |
  This is a Alex's Personal Blog. Tech, Sports, Books, that's all I want.

# The base hostname & protocol of your site for where absolute urls are needed
url: 

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl:

sass:
  sass_dir: _sass

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About Me
  url: /about/
- text: Style Guide
  url: /style-guide/
- text: Archives
  url: /tags/

# Author information - author info at the bottom of the post
author_name: "me"
author_bio: "Enthusiastic student studying front-end development, diving into the world of deep learning and iOS development. Sharing my journey and insights on my blog."
author_url: "https://dongckim.github.io/"
author_location: "Seoul, Republic of Korea"
author_image: IMG_1902.JPG

# Footer ad banner
banner_image: banner.jpg
banner_url: https://dongckim.github.io/

# Footer newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
facebook_username: "Dongchan Alex Kim"
github_username: "Dongckim"
instagram_username: "dck_alx"
linkedin_username: "Dongchan Alex Kim"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
